# Generated by Django 5.2.6 on 2025-12-22 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('coingecko_id', models.CharField(blank=True, max_length=100)),
                ('main_network', models.CharField(blank=True, max_length=50)),
                ('launch_year', models.PositiveIntegerField(blank=True, null=True)),
                ('liquidity_grade', models.CharField(choices=[('high', '상'), ('mid', '중'), ('low', '하')], default='mid', max_length=10)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('supply_total', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('supply_circulating', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('whitepaper', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='coins.coin')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='coins.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='coin',
            name='feature_tags',
            field=models.ManyToManyField(blank=True, related_name='coins', to='coins.featuretag'),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('is_avoided', models.BooleanField(default=False)),
                ('rank', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recs', to='coins.coin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성')], max_length=1)),
                ('risk_score', models.IntegerField(default=5)),
                ('trend_score', models.IntegerField(default=5)),
                ('avatar', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('avoided_sectors', models.ManyToManyField(blank=True, related_name='avoided_by', to='coins.sector')),
                ('preferred_sectors', models.ManyToManyField(blank=True, related_name='preferred_by', to='coins.sector')),
            ],
        ),
        migrations.AddField(
            model_name='coin',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='coins', to='coins.sector'),
        ),
    ]
