# Generated by Django 5.2.6 on 2025-12-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='risk_score',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='sector_score',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='trend_score',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
