# Generated by Django 5.2.6 on 2025-12-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_coinvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
